Make the version detection mechanism future-proof for MP update
loriswit/asl pull request #10
Opened 2021-11-24 03:45 UTC by EtaoinWu

The game update today (`1.10.2021.11.12.858.39`, but released on Nov. 23) broke it again. 

Hopefully the script still works; I have done zero testing.

2021-11-24 10:13 UTC, loriswit requested changes
Unfortunately, all earlier versions up to v1.10.2020.12.10 already had an Assembly-Csharp.ddl that was larger than 1.8 MB, so chances are this will just break earlier versions.

2021-11-24 10:21 UTC, loriswit commented
Maybe another way would be to check for the existence of some files, such as "level52" which only exists since the multiplayer update. However, this may just break the auto-splitter as well if people are trying to downpatch the game by overwriting existing files (which wouldn't remove new files such as level52).

2021-11-24 11:58 UTC, EtaoinWu commented
The code in the pull request only check the size of `Assembly-Csharp.dll` when the size of the `UnityPlayer.dll` module matches the one of the 2021 versions, which means that earlier versions will not break.

2021-11-24 12:29 UTC, loriswit commented
The "2021" version doesn't really match the game version, but rather the auto-splitter version (because it was updated in 2021). In fact, the game version 1.10.2020.12.10 also happens to be detected as "2021", and its `Assembly-Csharp.dll` is over 1.83 GB, so that version would stop working with this new auto-splitter update.

2021-11-26 00:58 UTC, EtaoinWu commented
Closed by commit [e0dc83d](https://github.com/loriswit/asl/commit/e0dc83d7cc9d02c5e0d0f75f231cd3b1960db055).

> Maybe another way would be to check for the existence of some files, such as "level52" which only exists since the multiplayer update. However, this may just break the auto-splitter as well if people are trying to downpatch the game by overwriting existing files (which wouldn't remove new files such as level52).

Although duct-taping (like we are currently doing) is not the most elegant solution, there isn't a clear way to future-proof the version setecting mechanism for now. I'll probably reopen this if we would find a pointer path to a version number string or something.

2021-11-26 00:58 UTC, closed without merging